### ISSUE TITLE
Change Directory while using  advcmd.CommandFolder property failing

### ISSUE THREAD

**Issue by ielshal** [xebialabs-community/xld-advanced-command-plugin#4]
In advcmd.CommandFolder when you upload artifact in which you can run commands specified in command section, deployment will fail because it can not chnage directory to path in which that artifact was uploaded, see below error,

```
ERROR c.x.d.plugin.steps.OsScriptStep - /tmp/ot-20170104T163616261/working.directory.tmp/advcmd/CommandRunner.sh: 5: cd: can't cd to local:/tmp/ot-20170104T163616261/working.directory.tmp/xld.9245/install-ssis.zip
```

After investigation i found this is due to that `${deployed.file}` evaluates to the uploaded file it self so according to scripts `CommandRunner.bat/.sh` being used in this plugin it is changing directory to deployed Artifact using `cd /d "${deployed.file}"` as below,

```
<#if deployed.file??>
REM do not remove - this actually triggers the upload
cd /d "${deployed.file}"
</#if>
```
So in order to resolve this and make it point to path of deployed package this need to be changed to `cd /d "${deployed.file.path}"`, I updated both scripts `CommandRunner.bat` and `CommandRunner.sh` "Other scripts like `NoopRunner.bat/.sh` also need to be updated "  then i tested this and found it is working as expected.

**Comment by jdewinne** [comment]
Thanks for reporting. Fixed this in [v3.2.1](https://github.com/xebialabs-community/xld-advanced-command-plugin/releases/tag/v3.2.1)
