### ISSUE TITLE
createOrder is ignored

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xld-advanced-command-plugin#5]
When only createOrder is used to set the value other than the default 60, then this is ignored. The value stays 60. 

When also noopOrder and/or destroyOrder are filled in, then the createOrder value is not ignored.
![image002-1](https://cloud.githubusercontent.com/assets/7237078/23449879/8aca1f60-fe58-11e6-9285-b754d70bc21d.png)
The attachment shows the value 102 when createOrder, noopOrder and destroyOrder are filled in.

**Comment by jdewinne** [comment]
Which version of the plugin and which version of XLD are you using?
I tried this, but get the expected result.
![screenshot from 2017-03-17 14-45-15](https://cloud.githubusercontent.com/assets/1579188/24064237/77613b0a-0b20-11e7-8eab-91fce5c4bfd5.png)

**Comment by ltutar** [comment]
XLD 5.1.4 and plugin version 3.2.0.

**Comment by jdewinne** [comment]
Can you perhaps share a deployment archive so I reproduce?

**Comment by ltutar** [comment]
I'll see what I can do on Monday.

**Comment by ltutar** [comment]
Hi Joris,

I sent the DAR to your e-mail account.
