### ISSUE TITLE
Artifact transfer on undeploy

### ISSUE THREAD

**Issue by mmajcica** [xebialabs-community/xld-advanced-command-plugin#6]
Dear,

is there a way to prevent the advcmd.DeployedCommandFolder to transfer the artifact on undeploy on the target system?
I am using you plugin to move an exe file on the target and trigger the installation. On undeploy, I'm uninstalling that application. What I do see is that on the undeploy the artifact is again transferred on the target system. I do not need it for the undeploy and it is a larger file 1Gb+.
Is there a way to prevent this?

Thanks
Mario

**Comment by jdewinne** [comment]
In theory, yes. As the [os-script](https://docs.xebialabs.com/xl-deploy/7.0.x/referencesteps.html#os-script) has a property called `upload-artifacts`. But disabling this, will most probably not work for many other use case.
So, I would strongly advice to create your own plugin and model this deployment in a separate one.

**Comment by mmajcica** [comment]
If I would still opt for disabling it, what is the change and it should be applied? Thanks

**Comment by jdewinne** [comment]
You can add the following into `xl-rules.xml`:
```
<disable-rule name="advcmd.DeployedCommand.DESTROY" />
<rule name="advcmd.DeployedCommand.DESTROY_TWEAKED" scope="deployed">
        <conditions>
            <type>advcmd.DeployedCommandFolder</type>
            <type>advcmd.DeployedCommand</type>
            <operation>DESTROY</operation>
            <operation>MODIFY</operation>
            <expression>previousDeployed.undoCommand</expression>
        </conditions>
        <steps>
            <os-script>
                <script>advcmd/UndoCommandRunner</script>
                <order expression="true">previousDeployed.destroyOrder</order>
                <upload-artifacts>false</upload-artifacts>
            </os-script>
        </steps>
</rule>
```

**Comment by mmajcica** [comment]
Thanks, it works!
