### ISSUE TITLE
Placeholders scan for advcmd.CommandFolder

### ISSUE THREAD

**Issue by mmajcica** [xebialabs-community/xld-advanced-command-plugin#7]
I do have some ps1 files zipped in the artifact I included with my advcmd.CommandFolder execution. Although I  set this file extension for File and Folder plugin in the deployit-defaults.properties file, file.File.textFileNamesRegex and file.Folder.textFileNamesRegex it has no effect on advcmd.CommandFolder.
How do I make advcmd.CommandFolder consider the ps1 extension for placeholders scan?

Thanks

**Comment by jdewinne** [comment]
The `advcmd.CommandFolder` isn't extending from the file plugin, but it is extending from the `udm` model. See also the [synthetic.xml](https://github.com/xebialabs-community/xld-advanced-command-plugin/blob/master/src/main/resources/synthetic.xml#L21).
So this means, you will have to change the `textFileNamesRegex` for the `advcmd.CommandFolder` in `deployit-defaults.properties`.
https://docs.xebialabs.com/xl-deploy/7.0.x/udmcireference.html#udm.BaseDeployableFolderArtifact

**Comment by mmajcica** [comment]
Hi Joris,

indeed, I'm sorry for such a banal question. A simple
`advcmd.CommandFolder.textFileNamesRegex=.+\.(cfg | conf | config | ini | properties | props | txt | asp | aspx | htm | html | jsf | jsp | xht | xhtml | sql | xml | xsd | xsl | xslt | ps1)`
did the trick.

Thanks
